
var __cov_ArTGEJZ8kKIBN3gbxoA0bw = (Function('return this'))();
if (!__cov_ArTGEJZ8kKIBN3gbxoA0bw.__coverage__) { __cov_ArTGEJZ8kKIBN3gbxoA0bw.__coverage__ = {}; }
__cov_ArTGEJZ8kKIBN3gbxoA0bw = __cov_ArTGEJZ8kKIBN3gbxoA0bw.__coverage__;
if (!(__cov_ArTGEJZ8kKIBN3gbxoA0bw['/home/hitesh96db/Documents/privly-jetpack/lib/extension.js'])) {
   __cov_ArTGEJZ8kKIBN3gbxoA0bw['/home/hitesh96db/Documents/privly-jetpack/lib/extension.js'] = {"path":"/home/hitesh96db/Documents/privly-jetpack/lib/extension.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":1,"7":0,"8":0,"9":0,"10":0,"11":0,"12":0,"13":0,"14":0,"15":0},"b":{"1":[0,0]},"f":{"1":0,"2":0,"3":0},"fnMap":{"1":{"name":"sendStartMessage","line":31,"loc":{"start":{"line":31,"column":0},"end":{"line":31,"column":43}}},"2":{"name":"(anonymous_2)","line":45,"loc":{"start":{"line":45,"column":12},"end":{"line":45,"column":29}}},"3":{"name":"(anonymous_3)","line":46,"loc":{"start":{"line":46,"column":41},"end":{"line":46,"column":59}}}},"statementMap":{"1":{"start":{"line":13,"column":0},"end":{"line":13,"column":37}},"2":{"start":{"line":16,"column":0},"end":{"line":16,"column":48}},"3":{"start":{"line":17,"column":0},"end":{"line":17,"column":20}},"4":{"start":{"line":20,"column":0},"end":{"line":20,"column":57}},"5":{"start":{"line":21,"column":0},"end":{"line":21,"column":45}},"6":{"start":{"line":31,"column":0},"end":{"line":37,"column":1}},"7":{"start":{"line":32,"column":2},"end":{"line":32,"column":19}},"8":{"start":{"line":33,"column":2},"end":{"line":35,"column":3}},"9":{"start":{"line":34,"column":4},"end":{"line":34,"column":18}},"10":{"start":{"line":36,"column":2},"end":{"line":36,"column":68}},"11":{"start":{"line":39,"column":0},"end":{"line":39,"column":36}},"12":{"start":{"line":42,"column":0},"end":{"line":50,"column":3}},"13":{"start":{"line":46,"column":4},"end":{"line":48,"column":7}},"14":{"start":{"line":47,"column":6},"end":{"line":47,"column":40}},"15":{"start":{"line":53,"column":0},"end":{"line":53,"column":35}}},"branchMap":{"1":{"line":33,"type":"if","locations":[{"start":{"line":33,"column":2},"end":{"line":33,"column":2}},{"start":{"line":33,"column":2},"end":{"line":33,"column":2}}]}}};
}
__cov_ArTGEJZ8kKIBN3gbxoA0bw = __cov_ArTGEJZ8kKIBN3gbxoA0bw['/home/hitesh96db/Documents/privly-jetpack/lib/extension.js'];
__cov_ArTGEJZ8kKIBN3gbxoA0bw.s['1']++;require('./first_run.js').firstRun();__cov_ArTGEJZ8kKIBN3gbxoA0bw.s['2']++;var {popupButton}=require('./privly_ui.js');__cov_ArTGEJZ8kKIBN3gbxoA0bw.s['3']++;popupButton.setup();__cov_ArTGEJZ8kKIBN3gbxoA0bw.s['4']++;var {postingProcess}=require('./posting_process.js');__cov_ArTGEJZ8kKIBN3gbxoA0bw.s['5']++;postingProcess.menuSetup(popupButton.button);function sendStartMessage(message,worker){__cov_ArTGEJZ8kKIBN3gbxoA0bw.f['1']++;__cov_ArTGEJZ8kKIBN3gbxoA0bw.s['7']++;var start='no';__cov_ArTGEJZ8kKIBN3gbxoA0bw.s['8']++;if(popupButton.getButtonState()==='active'){__cov_ArTGEJZ8kKIBN3gbxoA0bw.b['1'][0]++;__cov_ArTGEJZ8kKIBN3gbxoA0bw.s['9']++;start='yes';}else{__cov_ArTGEJZ8kKIBN3gbxoA0bw.b['1'][1]++;}__cov_ArTGEJZ8kKIBN3gbxoA0bw.s['10']++;worker.port.emit('privlyStart',JSON.stringify({'start':start}));}__cov_ArTGEJZ8kKIBN3gbxoA0bw.s['11']++;var data=require('sdk/self').data;__cov_ArTGEJZ8kKIBN3gbxoA0bw.s['12']++;require('sdk/page-mod').PageMod({include:'*',contentScriptFile:data.url('./content_scripts/privly.js'),onAttach:function(worker){__cov_ArTGEJZ8kKIBN3gbxoA0bw.f['2']++;__cov_ArTGEJZ8kKIBN3gbxoA0bw.s['13']++;worker.port.on('requestPrivlyStart',function(message){__cov_ArTGEJZ8kKIBN3gbxoA0bw.f['3']++;__cov_ArTGEJZ8kKIBN3gbxoA0bw.s['14']++;sendStartMessage(message,worker);});}});__cov_ArTGEJZ8kKIBN3gbxoA0bw.s['15']++;require('./run_test.js').runTest();
