
var __cov_P22aYjPfBXnTusyGm4nowg = (Function('return this'))();
if (!__cov_P22aYjPfBXnTusyGm4nowg.__coverage__) { __cov_P22aYjPfBXnTusyGm4nowg.__coverage__ = {}; }
__cov_P22aYjPfBXnTusyGm4nowg = __cov_P22aYjPfBXnTusyGm4nowg.__coverage__;
if (!(__cov_P22aYjPfBXnTusyGm4nowg['/home/hitesh96db/Documents/privly-jetpack/lib/run_test.js'])) {
   __cov_P22aYjPfBXnTusyGm4nowg['/home/hitesh96db/Documents/privly-jetpack/lib/run_test.js'] = {"path":"/home/hitesh96db/Documents/privly-jetpack/lib/run_test.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0},"b":{"1":[0,0]},"f":{"1":0},"fnMap":{"1":{"name":"(anonymous_1)","line":17,"loc":{"start":{"line":17,"column":7},"end":{"line":17,"column":18}}}},"statementMap":{"1":{"start":{"line":13,"column":0},"end":{"line":32,"column":2}},"2":{"start":{"line":19,"column":4},"end":{"line":19,"column":85}},"3":{"start":{"line":21,"column":4},"end":{"line":30,"column":5}},"4":{"start":{"line":24,"column":6},"end":{"line":24,"column":43}},"5":{"start":{"line":27,"column":6},"end":{"line":27,"column":71}},"6":{"start":{"line":29,"column":6},"end":{"line":29,"column":41}},"7":{"start":{"line":33,"column":0},"end":{"line":33,"column":29}}},"branchMap":{"1":{"line":21,"type":"if","locations":[{"start":{"line":21,"column":4},"end":{"line":21,"column":4}},{"start":{"line":21,"column":4},"end":{"line":21,"column":4}}]}}};
}
__cov_P22aYjPfBXnTusyGm4nowg = __cov_P22aYjPfBXnTusyGm4nowg['/home/hitesh96db/Documents/privly-jetpack/lib/run_test.js'];
__cov_P22aYjPfBXnTusyGm4nowg.s['1']++;var runTest={run:function(){__cov_P22aYjPfBXnTusyGm4nowg.f['1']++;__cov_P22aYjPfBXnTusyGm4nowg.s['2']++;var isTesting=require('sdk/preferences/service').get('extensions.privly.test');__cov_P22aYjPfBXnTusyGm4nowg.s['3']++;if(isTesting==='true'){__cov_P22aYjPfBXnTusyGm4nowg.b['1'][0]++;__cov_P22aYjPfBXnTusyGm4nowg.s['4']++;require('./xpcom.js').registerTest();__cov_P22aYjPfBXnTusyGm4nowg.s['5']++;const TESTPAGE='chrome://privly/content/test/test_loader.html';__cov_P22aYjPfBXnTusyGm4nowg.s['6']++;require('sdk/tabs').open(TESTPAGE);}else{__cov_P22aYjPfBXnTusyGm4nowg.b['1'][1]++;}}};__cov_P22aYjPfBXnTusyGm4nowg.s['7']++;exports.runTest=runTest.run;
